server:
  port: ${PORT_APP:9191}
  servlet:
    context-path: /doctor

spring:
  application:
    title: Microsservico Doctor
    version: 1.0
  datasource:
    url: jdbc:${DB_SGDB:postgresql}://${DB_HOST:localhost}:${DB_PORT:3000}/${DB_NAME:doctor}?currentSchema=${DB_SCHEMA:hackaton}
    username: ${DB_USER:doctor}
    password: ${DB_PASSWORD:doctor}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
api:
  security:
    token:
      secret: ${JWT_SECRET:123456789}
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
